### ISSUE TITLE
Keycloak 26 keep restarting in Kubernetes environment

### ISSUE THREAD

**Issue by edwin** [keycloak/keycloak-quickstarts#698]
### Describe the bug

Keycloak keeps restarting because port 9000 is not being able to accessed during Probe, 
this is due to Keycloak is taking a while for starting especially when forming a cluster with another Pod or when loading lots of custom SPI.

https://github.com/keycloak/keycloak-quickstarts/blob/4e5305e834abb3e4161c0bd9048f5887389f6916/kubernetes/keycloak.yaml#L104-L115

would be great if we could add some initial delay before starting Probe as a default values
```yaml
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
            failureThreshold: 3
```

### Version

26

### Expected behavior

Keycloak should be running perfectly well

### Actual behavior

Keycloak keeps restarting

### How to Reproduce?

use this file
https://github.com/keycloak/keycloak-quickstarts/blob/main/kubernetes/keycloak.yaml

but with lots of custom SPI within the Keycloak image to simulate a slow start 
and we can see Keycloak would keeps restarting after a while

**Comment by vmuzikar** [comment]
@edwin Thank you for the report. The quickstart is meant to be updated by the user for their specific environment, it's just a starting point as the name suggests. :)

CC @shawkins

**Comment by shawkins** [comment]
@edwin can you create a pr with updates to the probe values? The operator for example uses:

```
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
            periodSeconds: 1
            failureThreshold: 600
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
            periodSeconds: 10
            failureThreshold: 3
```
